### ISSUE TITLE
Should we 'version control' bodyHTML field?

### ISSUE THREAD

**Issue by andygnewman** [Financial-Times/next-es-interface#398]
We've migrated many article transformations upstream from article into next-es-interface and created bodyHTML from bodyXML.

The concept was to have bodyHTML reasonably non-opinionated and consequently relatively stable.

Some non-Next teams have started using bodyHTML and have some dependencies on the structure of it that differs from Next dependencies. Consequently any changes to bodyHTML may break things for non-Next users. (I have a set of small PRs to improve the consistency of the HTML, which would have done this).

Should we;

a) Create some method of version controlling that can have more than one version of bodyHTML available at any point in time (eg. a stable and changed version).

b) Retain only one version, but ensure communication and timescales enable users to accommodate any forthcoming changes.

My preference would be b);
- the elastic search cluster is a next tool and other users use it at their own risk
- maintaining versions of a field in ES is not a standard approach
- it would be the same approach that we get from the underlying APIs

Happy for any views in support / contradictory to this view, especially @matthew-andrews, @i-like-robots, @georgecrawford

**Comment by i-like-robots** [comment]
Definitely B.

> the elastic search cluster is a next tool and other users use it at their own risk

Yep, it's scratching our itch. Hopefully things will be upstreamed into CAPI.

**Comment by matthew-andrews** [comment]
because of the way we ingest content we have to maintain a certain amount of backwards compatibility for at least a week — so that stops us going **too** crazy with B.

**Comment by richard-still-ft** [comment]
I'm happy with B but really think we should banish all talk of API v3 and strongly encourage other consumers to spin up their own ES clusters or do something else. The the probability of a team creating a product using Next ES and that product being orphaned is high. At some point we might find lots of things breaking without teams in place to fix them.

**Comment by rowanbeentje** [comment]
Another vote for B.

@richard-still-ft: I hear you on the separation/support front for teams spinning up their own ES clusters, but isn't there also a bit of a cost overhead for new ES clusters - both in financial and staff costs?  The Next cluster currently costs thousands per month and I imagine an apps one would be basically equivalent, plus also the monitoring/updates/fixes etc time... 😨  I'd rather have to update quickly than have the danger of it not updating at all, I think.

**Comment by matthew-andrews** [comment]
Also, 'V3' should not be mentioned anymore, we should refer to it as 'Next's Content API'.

**Comment by richard-still-ft** [comment]
The next cluster is ripe for cost reduction now that we use it more efficiently. AMP should be getting a very good cache hit rate so the cluster size you would need should be tiny. Running one massive cluster than can cater to a wide variety of needs is a _very_ expensive way to operate a cluster. We have seen that an entire ES cluster (running on substantial hardware) can be swamped by a single expensive query. 

For Next this potentially exposes multiple platinum applications to a high degree of risk which I think is a bad idea. It should be perfectly possible to provision a cluster from scratch including all the monitoring by building on the work that @matthew-andrews has already done. What is missing are the APIs to more simply allow the population of a cluster from scratch using a schema of the consumers choice. 

@rowanbeentje It's fine to say you would rather update a thing quickly but we frequently put apps out to pasture and the people who understand them move on or leave and so making changes becomes much more difficult. That _shouldn't_ happen but it's not likely to change any time soon. Although I guess you could equally say that about the infrastructure...

**Comment by i-like-robots** [comment]
> What is missing are the APIs to more simply allow the population of a cluster from scratch using a schema of the consumers choice

It's not too hard actually... I've imported 'slices' of data into a locally running ES instance and we have to create a new index whenever we wish to change settings. I've documented the process here: https://github.com/Financial-Times/next-es-interface/wiki/Reingesting-content

**Comment by richard-still-ft** [comment]
@i-like-robots that looks very helpful. Ultimately It would be nice if UPP had these APIs though so that there was a way to index content from the canonical source. Those APIs would need to be coupled to a more usable setup of UPP APIs though. 

Any use of one product's Content API by another because the underlying APIs are flawed is fundamentally wrong.

**Comment by rowanbeentje** [comment]
@richard-still-ft We currently use the next cluster for AMP, for Facebook Instant, and for the Web App instead of going directly to CAPIv2, to take advantage of all the transforms happening there.

To be honest I'm more concerned about the staff overhead concerned with running the platform than any incremental dollar cost.  We've got three uses of the platform here so I agree that in an ideal world we'd have three new instances, putting an extra maintenance burden on us which is likely to be significantly higher than the cost of keeping up with changes (even if they're put out to pasture!).

Matt B also made the excellent point that when spinning up new projects very quickly, like the distributed apps and their shortened timelines, being able to use existing infrastructure is much much faster than having to spin up a new API layer each time.

Agreed that it'd be nice if there was an underlying layer which handled all this - and I do get the impression that's the long-term goal.

**Comment by matthew-andrews** [comment]
Closing.  Think the consensus is to **not** version control `bodyHTML` … for now …
